class EmailSender < ActiveJob::Base
  @queue = :emails_queue

  def perform(params)
    puts "asdasdasdsasdsadsadsadsaddsadsdadsadadasdasdadsadasdadsadsadasdsadsadasdasdasdsadsadsaaddsadsadsadsadsadsadsadsadsadsadsadas"
    puts "asdasdasdsasdsadsadsadsaddsadsdadsadadasdasdadsadasdadsadsadasdsadsadasdasdasdsadsadsaaddsadsadsadsadsadsadsadsadsadsadsadas"
    puts "asdasdasdsasdsadsadsadsaddsadsdadsadadasdasdadsadasdadsadsadasdsadsadasdasdasdsadsadsaaddsadsadsadsadsadsadsadsadsadsadsadas"
    puts "asdasdasdsasdsadsadsadsaddsadsdadsadadasdasdadsadasdadsadsadasdsadsadasdasdasdsadsadsaaddsadsadsadsadsadsadsadsadsadsadsadas"
    puts "asdasdasdsasdsadsadsadsaddsadsdadsadadasdasdadsadasdadsadsadasdsadsadasdasdasdsadsadsaaddsadsadsadsadsadsadsadsadsadsadsadas"
    puts "asdasdasdsasdsadsadsadsaddsadsdadsadadasdasdadsadasdadsadsadasdsadsadasdasdasdsadsadsaaddsadsadsadsadsadsadsadsadsadsadsadas"
    puts "asdasdasdsasdsadsadsadsaddsadsdadsadadasdasdadsadasdadsadsadasdsadsadasdasdasdsadsadsaaddsadsadsadsadsadsadsadsadsadsadsadas"
    puts "asdasdasdsasdsadsadsadsaddsadsdadsadadasdasdadsadasdadsadsadasdsadsadasdasdasdsadsadsaaddsadsadsadsadsadsadsadsadsadsadsadas"
    puts "asdasdasdsasdsadsadsadsaddsadsdadsadadasdasdadsadasdadsadsadasdsadsadasdasdasdsadsadsaaddsadsadsadsadsadsadsadsadsadsadsadas"
    UserMailer.welcome_email(params).deliver_later
  end

end
